spring.application.name=hng-stage-zero

# logging levels
logging.level.root=INFO
logging.level.com.osato.hngstagezero=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
